// actionTypes user 

export const SIGN_UP="SIGN_UP";
export const SIGN_UP_FAIL="SIGN_UP_FAIL";
export const SIGN_UP_SUCCESS="SIGN_UP_SUCCESS";

export const LOGIN="LOGIN";
export const LOGIN_FAIL="LOGIN_FAIL";
export const LOGIN_SUCCESS="LOGIN_SUCCESS"


export const GET_PROFILE="GET_PROFILE";
export const GET_PROFILE_FAIL="GET_PROFILE_FAIL";
export const GET_PROFILE_SUCCESS="GET_PROFILE_SUCCESS";

export const GET_ALLUSERS="GET_ALLUSERS";
export const DELETEUSER = "DELETEUSER";
export const BLOCKUSER="BLOCKUSER"


export const LOGOUT="LOGOUT";


// actionTypes product 

export const ADDPRODUCT = "ADDPRODUCT" ;
export const ADDPRODUCT_SUCCESS = "ADDPRODUCT_SUCCESS" ;
export const ADDPRODUCT_FAIL = "ADDPRODUCT_FAIL" ;

export const GETPRODUCTS = "GETPRODUCTS";

export const UPDATEPRODUCT = "UPDATEPRODUCT";
export const DELETEPRODUCT = "DELETEPRODUCT";

export const DETAILPRODUCT = "DETAILPRODUCT";
export const DETAILPRODUCT_SUCCESS = "DETAILPRODUCT_SUCCESS" ;
export const DETAILPRODUCT_FAIL = "DETAILPRODUCT_FAIL" ;

export const GET_SOFA_PRODUCT = "GET_SOFA_PRODUCT";
export const GET_CHAIR_PRODUCT = "GET_CHAIR_PRODUCT";
export const GET_MOBILE_PRODUCT = "GET_MOBILE_PRODUCT";
export const GET_WATCH_PRODUCT = "GET_WATCH_PRODUCT";
export const GET_WIRELESS_PRODUCT = "GET_WIRELESS_PRODUCT";

// action types cart 

export const CARD_ADD_ITEM = "CARD_ADD_ITEM";
export const CARD_ADD_ITEM_SUCCESS = "CARD_ADD_ITEM_SUCCESS";
export const CARD_ADD_ITEM_FAIL = "CARD_ADD_ITEM_FAIL";


export const GET_CARD_ITEM = "GET_CARD_ITEM";




export const CARD_REMOVE_ITEM = 'CARD_REMOVE_ITEM';
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';